{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red191\green131\blue194;\red34\green34\blue34;\red193\green193\blue193;
\red135\green135\blue135;\red109\green188\blue135;}
{\*\expandedcolortbl;;\cssrgb\c80000\c60000\c80392;\cssrgb\c17647\c17647\c17647;\cssrgb\c80000\c80000\c80000;
\cssrgb\c60000\c60000\c60000;\cssrgb\c49412\c77647\c60000;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 backend\cf4 \strokec4 :\
  \cf2 \strokec2 name\cf4 \strokec4 : git-gateway\
  \cf2 \strokec2 branch\cf4 \strokec4 : master \cf5 \strokec5 # Branch to update (optional; defaults to master)# This line should *not* be indented\cf4 \strokec4 \
\cf2 \strokec2 publish_mode\cf4 \strokec4 : editorial_workflow
\fs32 \
\pard\pardeftab720\partightenfactor0

\fs28 \cf5 \strokec5 # This line should *not* be indented\cf4 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec2 media_folder\cf4 \strokec4 : \cf6 \cb3 \strokec6 "images/uploads"\cf4 \cb3 \strokec4  \cf5 \strokec5 # Media files will be stored in the repo under images/uploads
\fs32 \cf4 \strokec4 \
\pard\pardeftab720\partightenfactor0

\fs28 \cf5 \strokec5 # These lines should *not* be indented\cf4 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec2 media_folder\cf4 \strokec4 : \cf6 \cb3 \strokec6 "static/images/uploads"\cf4 \cb3 \strokec4  \cf5 \strokec5 # Media files will be stored in the repo under static/images/uploads\cf4 \strokec4 \
\cf2 \strokec2 public_folder\cf4 \strokec4 : \cf6 \cb3 \strokec6 "/images/uploads"\cf4 \cb3 \strokec4  \cf5 \strokec5 # The src attribute for uploaded media will begin with /images/uploads
\fs32 \cf4 \strokec4 \

\fs28 \cf2 \strokec2 collections\cf4 \strokec4 :\
  - \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "blog"\cf4 \cb3 \strokec4  \cf5 \strokec5 # Used in routes, e.g., /admin/collections/blog\cf4 \strokec4 \
    \cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Blog"\cf4 \cb3 \strokec4  \cf5 \strokec5 # Used in the UI\cf4 \strokec4 \
    \cf2 \strokec2 folder\cf4 \strokec4 : \cf6 \cb3 \strokec6 "_posts/blog"\cf4 \cb3 \strokec4  \cf5 \strokec5 # The path to the folder where the documents are stored\cf4 \strokec4 \
    \cf2 \strokec2 create\cf4 \strokec4 : \cf2 \strokec2 true\cf4 \strokec4  \cf5 \strokec5 # Allow users to create new documents in this collection\cf4 \strokec4 \
    \cf2 \strokec2 slug\cf4 \strokec4 : \cf6 \cb3 \strokec6 "\{\{year\}\}-\{\{month\}\}-\{\{day\}\}-\{\{slug\}\}"\cf4 \cb3 \strokec4  \cf5 \strokec5 # Filename template, e.g., YYYY-MM-DD-title.md\cf4 \strokec4 \
    \cf2 \strokec2 fields\cf4 \strokec4 : \cf5 \strokec5 # The fields for each document, usually in front matter\cf4 \strokec4 \
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Layout"\cf4 \cb3 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "layout"\cf4 \cb3 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf6 \cb3 \strokec6 "hidden"\cf4 \cb3 \strokec4 , \cf2 \strokec2 default\cf4 \strokec4 : \cf6 \cb3 \strokec6 "blog"\cf4 \cb3 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Title"\cf4 \cb3 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "title"\cf4 \cb3 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf6 \cb3 \strokec6 "string"\cf4 \cb3 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Publish Date"\cf4 \cb3 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "date"\cf4 \cb3 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf6 \cb3 \strokec6 "datetime"\cf4 \cb3 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Featured Image"\cf4 \cb3 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "thumbnail"\cf4 \cb3 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf6 \cb3 \strokec6 "image"\cf4 \cb3 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Rating (scale of 1-5)"\cf4 \cb3 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "rating"\cf4 \cb3 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf6 \cb3 \strokec6 "number"\cf4 \cb3 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf6 \cb3 \strokec6 "Body"\cf4 \cb3 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf6 \cb3 \strokec6 "body"\cf4 \cb3 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf6 \cb3 \strokec6 "markdown"\cf4 \cb3 \strokec4 \}
\fs32 \
}