{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red193\green193\blue193;
}
{\*\expandedcolortbl;;\cssrgb\c0\c1\c1;\cssrgb\c100000\c100000\c99985\c0;\cssrgb\c80176\c80176\c79976;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
backend:\
  name: git-gateway\
  branch: 
\fs28 \cf2 \cb3 master # Branch to update (optional; defaults to master)
\fs32 \cf2 \cb3 \
\
media_folder: assets/img\
public_folder: /img\
\
collections:\
  - name: 'projects'\
    label: 'Projects'\
    folder: 'content/projects'\
    format: 'frontmatter'\
    create: true\
    slug: '\{\{year\}\}-\{\{month\}\}-\{\{day\}\}-\{\{slug\}\}'\
    editor:\
      preview: false\
    fields:\
      - \{ label: 'Title', name: 'title', widget: 'string' \}\
      - \{\
          label: 'Short Descripcion',\
          name: 'short_description',\
          widget: 'string',\
        \}\
      - \{\
          label: 'Long Description',\
          name: 'long_description',\
          widget: 'string',\
        \}\
      - \{\
          label: 'Tags',\
          name: 'tags',\
          widget: 'select',\
          multiple: true,\
          min: 1,\
          max: 3,\
          options: ['Social Media Design', 'Web Design', 'Art Direction'],\
        \}\
      - \{\
          label: 'Thumbnail',\
          name: 'thumbnail',\
          widget: 'image',\
          allow_multiple: false,\
        \}\
      - \{\
          label: 'Project Images',\
          name: 'images',\
          widget: 'object',\
          fields:\
            - \{label: 'RRSS Images', name: 'rrss', widget: 'image', allow_multiple: true, \}\
            - \{label: 'WEB Images', name: 'web', widget: 'image', allow_multiple: true, \}\
        \}}