{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Monaco;
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red193\green133\blue195;
\red194\green194\blue192;\red136\green136\blue135;\red191\green131\blue194;\red34\green34\blue34;\red193\green193\blue193;
\red109\green188\blue135;\red135\green135\blue135;}
{\*\expandedcolortbl;;\cssrgb\c0\c1\c1;\cssrgb\c100000\c100000\c100000\c0;\cssrgb\c80724\c60725\c80740;
\cssrgb\c80437\c80436\c79935;\cssrgb\c60328\c60327\c59951;\cssrgb\c80000\c60000\c80392;\cssrgb\c17647\c17647\c17647;\cssrgb\c80000\c80000\c80000;
\cssrgb\c49412\c77647\c60000;\cssrgb\c60000\c60000\c60000;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 backend\cf2 \strokec5 :\
  \cf2 \strokec4 name\cf2 \strokec5 : git-gateway\
  \cf2 \strokec4 branch\cf2 \strokec5 : master \cf2 \strokec6 # Branch to update (optional; defaults to master)
\fs32 \cf2 \strokec5 \

\fs28 \cf7 \cb8 \strokec7 publish_mode\cf9 \strokec9 : editorial_workflow
\fs32 \

\fs28 \cf7 \strokec7 media_folder\cf9 \strokec9 : \cf10 \cb8 \strokec10 "images/uploads"\cf9 \cb8 \strokec9  \cf11 \cb8 \strokec11 # Media files will be stored in the repo under images/uploads
\fs32 \cf9 \cb8 \strokec9 \

\fs28 \cf7 \strokec7 media_folder\cf9 \strokec9 : \cf10 \cb8 \strokec10 "static/images/uploads"\cf9 \cb8 \strokec9  \cf11 \cb8 \strokec11 # Media files will be stored in the repo under static/images/uploads\cf9 \cb8 \strokec9 \
\cf7 \strokec7 public_folder\cf9 \strokec9 : \cf10 \cb8 \strokec10 "/images/uploads"\cf9 \cb8 \strokec9  \cf11 \cb8 \strokec11 # The src attribute for uploaded media will begin with /images/uploads
\fs32 \cf9 \cb8 \strokec9 \
}
